SPAMTRIX_PATH = c:/work/SpaMtrix



#COMPILE OPTIONS
#OPTIONS += -DUSES_OPENMP -fopenmp
#OPTIONS += -march=native -mtune=native
OPTIONS += -DDEBUG -g
#OPTIONS += -O3 



CXXFLAGS += $(OPTIONS) -Wall -std=c++0x
#CXXFLAGS += -fPIC


INCLUDE_PATH = $(SPAMTRIX_PATH)/include
LIBRARIES_PATH = $(SPAMTRIX_PATH)/lib